AaAAaAAAAaAAAAAaAaAaaAAaAaaaaAAaaAaaAaaaaaAaaaaAAAAAaaaAaaAAAaaaaAAAaaAAaaaAAaaAaaAaaAaaaaAAaaAAaAAaaAAAaAaAAaaAaAaaaaAaAAaaaaaAAAAAAaAaAAAaAAaaaaaaaAAAaaaaaAaAaAAaAaAaAaAaaAaAaAAAaaAAaaaaAaaaaAaaaAaaAaAAaaAAaAAAAAaAaAaaaaAAaAaAAAaaAAAAAAAAAAAA = "KObWIpFDHonMjXsIhOAlYxXVAZiuJfYPNAooAcSsZdEaKqsmAcZRnTGdaRqafHmSwMKkYjDghbyjNCZ"
lIlIlIlIlIIIIlIlIIIIIlIllIlIIIllIIIlIlllIllIIIIlIIllllllllIIIIllIIIIIIlIIlllIIlIIlIlIllIlllIIllIIIlllIlIlIIIllllIIIIllIIllIIlIIlIlIIlllllIIIlIlIlIlIIllIllIIIIIlIlIllllllIIlIIIIIIIlIIlIIlIlllIlIllIlllIIllIlllllIlIllIIIlllIIIlIlIlIllIlIIllIllIl = 400
VjVlurtsRuazvkVyZslxFTpdETUyzWhWHVzGmpyBDxAUpFqGkreWwQWLbKvkrGvAqycyWHxVsNDnGVt240 = "sHpVLpDiyDVwdAIkKUqhqWWjRTYUPmYHwgUGJCgNAOCtRuvOWdDAacgDNXbgsRhtbxUJijnjySwxDLT"
I16822114530414667238 = 298
KXHqvzNrYmgbcuyxMXPBqesZWNZofgKXYwYBLECUIfqTTpNUvdkXsFJGsjlBjEarjZIPrRPkJhYulWa236 = 361
Q16822114530390284234 = 264
e16822114530372083232 = 466
C230 = 254
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX = "YtUNsVERCRXoNDoXEOqCveXUBgBiwCGELPVyZJDdbWdNCkmEguUYBkHfLXejuCrtoPPsRfzSnkhHGYd"
AaaaaaaaAAAAaaAaaaAAaAAaaaAAAaAaaaAaAAaAaAAaAAAAaAAaaaaAAAAAAAAAaaAAaaaAAAaaaAAAaaaaAAAaaAaAAaAaaaAAAAaAaAAAaaAaAAAAAAAAAAaAAaaaAaAaAaaaAaaAAAaAaAaAAAaAAaaAAaaaaaAaaaAAAAAAAAAaAaAAaaaAAaaaAaAaaaAAAAaaaaaaAAaaaAAaAAaAaAaAAAAAAa = "aOczqydhAPktRWVPcwPMSDTwiVKPFuwHLxeWLgOgHNyNoFhGqIeFkPaYVPAhgtMPZhVLOMJdjDuXRJI"
ONvkZUWNklgxWdgEIFlyJziBsIVHOTPVUzJtlLBUcVnhcLgRQQZZwGQRupEMJNnopdcRLSXbOvgfmlG224 = "oSUTebkVnAhYuNmGSsStyDheYbPsodslgsDUiSqkqLgIGlLzCltIJLGxSIyuObRLXngxHRiVnwDNiOP"
Q222 = 396
lbOyMlkqecVjDumBvqBbuuAaWIBrHmSQEycrABlNZnygYLgVmKzUlfeDcXzIfzshxZzPIwYaMagJDNE220 = 244
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = 276
k16822114530262978216 = 204
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = 430
hWAnrCmUEudYRhevcWmrgVraLWimCPNrYLvmcEaHgPOsGgSZgRGrNOUxfyfAQhQfFlVqaclohsVNeri212 = 726
j210 = "ZQnGxiprCuHfhEjPSWAanpLdmXzRVzjulhHRfatxSNQpcMPzeniyqFiPLdRWUeBOLcfBLQKBpVorEFG"
lllIIlIIllIIIIIIlIlIllllIllIlIlIIIllIIlllllIlllllllIIIlIlllIIIlIIIlIIIIIIIllllIlIIIIlIlIIllllIIIIIlIIlllIIlIllIIlIIlIIlIlIlIlIllIllIlIllllIllllllIIllIlllIIllllIllIIIIIIlIIlIIIllIlIIIIlllIIlIIIlIlllIIllIllIlIl = "gmtnCcQgybeQARWayyKnhGwTNQtEbQZOvhbPwUCuWoDugLEOlEQcxQifuTWtZGVowAsjOnTSskvOufU"
cwVyeWIywEaOudnJppJAPBkQmTZoiQWznBNQprhgweEvLphRvXangOxtnTSnrrsFgkHhsStrwxWDrAU206 = "sIqIIuETKwohHduFkqrWSKBeCBOwqzuufQeBoVbisspnnfEQqXgutYzMVQZeBTrHjKwWxPTimWkwZZd"
llIlIlIIlIIIIIIlIIIIIlIllIlIlIIlIIIIIIIllIIllllIIIlIIlIllIIIlllIlIllIIIIlIIlIlllllIIlllIlllllIIIlllIlIIIIllIIIIllllllllIlIlllIlllllIIllIlIIlllIlIllIIIIlllIIIllIlIlIIIllllllIllllIIIllIllIIIIllllllIllIllIlI = "PIaxHMRgEfJilhFdtthkbVsoRdwEFHuyhdSZnaRkUkOCRphveyrfMDiMVNAYRLVORKvVURQkWjgVJuX"
lIIIIlIlIlIIIIIIIIIlllIllIlIIlllllIIlIIlIllIIIIlIlllllIllllIIIIIIlIllllIIIlIlIIIlllllIlIllllIIIIIIIlIIlllIlllIIllllIIlllIlIllllllllIIlllllIlIIlIlIllIlIlllIllIlIIIIIllIllIllllIIlIIlIIlIIlllllllIlllIlIIIl = "febaxJCCzBTAAZYMviDxzjkrNyPdkdDUHWpXlEIYpsdRQwDEkUuNxiZSBmqtfPVLKowkHyfGuVttpnA"
lIIlIlIIlIlllIIlllIIIlllIllIllIIlIlIlllllIlllIIlIlIlllIllllIIIIIIIIlIIlIIlIlIIllIlllIllllIllllllIIlIllIIlllIIIIIIlIIIlIllIlllIIllIlllIIIIIllIIlIIlIIlIlllIIIIIIIlIlIIlIlIlIlIlIIlIIIIIllIIlIllIIlIllIIll = 474
AaAaAaaAaAaAaaAaaAAAaaAaaaAaAaaAAaaaAaaAaaaaaaaaAaaAaaaaaAaaaaAaAAAAaAaaaAaaAAaAAAaAaAaAaaaAaAaAaaaAAaaAaaAaaaaAAaAAAAAaAAaAaAaAaaaaAAaaAaAAAAAAAaaAAAAaAAAAaaaAAaAaaAAaAaaaaAAAAAAAAaAaaaaaAAAaAaAaaA = 335
W168221145301038196 = 632
q1682211453009755194 = 512
eZTgcXdYOgryiSeDVLnioSlHIUAxohZNIqhNIoDbpDypMPbBONbRVVEebmRwCRuCPCKZvrQGeUQvtLe192 = 751
aaAAaaaaAAaaAaaaAaAaAaAaAaAAAaAaAAAaAAaAAAaAAAaaaaaAAAaaaAaAAaAAaaaaAAaaAAaAAAaAAaAaAaaAaaaAaAaAaaAaAaaAaAAaaAaaaaaAaAaaaaAaAaaaaaAAaAAAAaaaaAaaaAaAaAaAAaaaaaAAaaaaAAAaAAAaAaaAAAaaaaaaaaAaAa = "sAarUrSWhHoZqxyoZuSFAcWyEGKRgNdVOuLqOHYECWOpNpGmOLhTGHQZZFKJLUopVejbnwRUNOOTXNG"
jkevBWSoRdOdNGywUFovHWZjMJeiDBfpEeyVMxWNnbEpdhUuRTwTTNgRJGsihomZRPkvpFRcCYdYVNL188 = "eHHtGlnwHpgNAFFuIELuFZiwAegCDJzMrCOxitrOXIKcgmneoclalKALuVkNOxkXZiIOLavFjSfedtY"
aaaAaaaAAaaAaaAaaAaAaaaAaaaAAAAaaAaaaaaAaaaAAAaaaAaaAaaAaAaAAAAAAaaAaAAaAaAAAaAAAaaAAAaAaAAaaaaaaAAaaaAAaAaaaaaaaAaAaAAAaaaAAaaaAAaAaaaAAaaAAaAAAaAAAAaAAaAaaaaAaAaaAaaAAAAaaaaaaAaaaaaAAA = "wsiUgcljtdoKAmJsNccLTNiENIAQgGwDzRPOzBLmxuhAjsStBNZdEdOIebUfYmSWRHDZcCPRvQmixUv"
llIllIlllIIIIIIlIlIlIIllllllllIIlIIlllIIlllIlllIIlIlIlIllIllIlllIllllIIllIlIIllIllllIlIlllIlIIlIIIlIIIlIlIlIlIlIIIIIIlllIlIIIlIIllIIIIlllllIIIlllIIIIllIlIlIIIIIlllIIIlllIIIIIlllllllIlI = 287
IIlllIlIIlllIIlIIIllIIIIllIlllIlIIllIIIllllllIlllIlIlllIlIllIlIIIlIlIllIIlllIlIIllIllIIIIlllllllllllIIIIIIIlIllllIllIIIlIlIlIlllIIIIIIlIIIIllIIIIlIlIllIIlIllIIlllllIlllllIIIlIIlllllI = "EzSpZydHLytVlLykBLTDhFBsDcSBkEdzRUxCHhJuciDyfqNjVuvDuuGqZISkqrZBBnROMTNKGTKgfuI"
g16822114529987383180 = "IxByGSfussbiwbKVOvmVltetSXbviUCHnuqZvUuhHThsBRGqsvPVrqiHzeqwhQXZyNkqQGWohsWtoKT"
xKqZOPTDmgaBhrUfPdlyMJwHrCALCqEWrsPFjIudnuZaXDTQnxlFkeAWkNuotYuPLTLNxFcwGHaiGBX178 = 366
W16822114529967136176 = 103
AaAaAAaaaaAaaAAAaAaAaaaaAaaAAaAaaAaaaAAaaaaaaAaaaaAAAaaaaaAaAAAaaaAAaaAAaAaaAAaAaaaaAAAAAaaaaAaaAAaaAaAaaAaAaaaAaaaAAaaAaAaAaaaAAAaaaAAAaAAaAaAaAaaaaaaAAaAaaaaAaaAAaaAaaaAaaa = 353
IIIlIllllIllIlIIIIlIllllIlllIllIIlIlIIlIIIIlIIIIlIllllIIlIIIIlIIIIIlIlIIIllIIlIllIlIIllIlIlIIIIlIIllllllIlllIllllIlIlIIIIlIIIIlIIIIlIlIlIlllIlIIIIlIlIIIIlllIIIIlIIIllIIIlII = 656
iSrvqLSVdRHKRgQOPaJXwhMsZYVdiJtTmfBUVBycCiYsqTeMmWpaYHjamLyHJRzFTUNYymMsfmjxzwv170 = 269
z168 = 902
T166 = "iHiTHeXLzcMedVWbtfFzCCNmiwcuozfaNiqeeFskydgNEPbXgyyyWQLFPgfxAKcJLvTdxtloNpavikG"
IllIllIllllIIIIlIIlllIIIlIllIIllIlIllllIIllllIIllIllIIlIIIlIlIIIlIIIllIIIllIllllIlIIllIlIIIIlIIIllIIIIIIIIllIIlllIIIlIIlIIIllIlllllllIIlIIlllIllIlllIlIllllllllIllll = 458
llIlIlIlIIlllIllIlIllIIlIIIllIlIIIlllIlIllllllIlllllllIIIIIllIIlllllllIllIIlIIIllllIIIIllIllIIlIlIIIlIlIIllIlllIIllIlllIIlIlIIIlllIllIIIlllIIIlIllIIIllIIlIIlIlllI = 414
llIIllIlIllllIIllllIlIlIlIlllIlIlIIlIllIlIIIIlIIIIIIllIIlIlIlIlIlIllIIlllIIIIIlIIIlIIlllIIIIllIIIlllIIlIllIlIlIlIlIIIlIIllIlIIIlIlIlIIIIlIIIIlIIIIllIIIIllllIlll = "MAgyHQGoQGTIsjaunonRxBiOHFlZlEaWERgrVeMgmPyVkLgbZvvvxMcEDPBjHcmWPFOXqNPgkKstkOc"
IllllIlIlIllIIIIlIlIIlIIIlIlIlIIllIlIIIlIIllIlIlIIIlIIIIlIIIIlIllIIlIIlIIllllIIllIlIIIIlIIIllIIIIlllllllIIlIllIllIIllIlllIIlIIlllIllIIlIllllIlIIlIlIIllIIlllIl = "mIjvpLndScgBkNzvDSblBqNNPgdwROpjuoOBeznAlUbTnViajdrKDlVbAyIfWrycoqhQCQxmollssmI"
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = 667
Q16822114529799702154 = 332
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff = 700
T16822114529789321150 = "ZiQTMQHJRisYOSBcMsMDBJLWuYtHkUqAbNEBIJNRcSYFBaJnzQAMpzesTEdKhNrsWdkSBOVxTPfCvFO"
OiTwCBdboFzyWDBukNOgFtFewiFBvhGVpGlmHPeejzlAONRInhzEKbtxugNWjErxeiqcOBubWsPWzvX148 = "XnRsvDnrbMTytTzoekhpHDQxZAdKyFmzZWjQcDIKDGBRTXKvaEbaryzsEcEzpNFgfJJNcOccwOJanWJ"
AaaAAAAAaaaaaAaAAaAAAaaaAaaaaAAaaaaaaAAaaAaaaaAAAAaAaAAaAAaAaAaaaaAaAAaaAAAaaAAAAaaaaAAaAaaaAAaAaAaAaaAAaAaaAAaaAAAaaaAAAaAAaaAAaAAaAaAaAAAAaAaAAa = 418
g144 = "aLPoYHeKFCiNNkSZGwcHLKOySwgHJPJyDRZJcuCIVFBmeIIoFLUTITTIkVYdpinHgymQOxgusSGQobw"
kApqDgHOHeQOKzyuuNQFmpKGxWdIowUiqEttQsNPvofYpANkhWcrWRBwpyMTukmslWqhavyoPTMUiiE142 = "ERjQPBYMOkmEhSQuynojrGJXqWdnxCuYdRAnMasXHZkSTqEnEmgmUWopDcFtnTzlOlyNAFAIwWrPJnu"
TcdZNtBTfLEDMNurFPFvYGcHlHBujZcCaaLSpyRRCRMuVUmAeHShHIawWJLkjPIfCLcKJwzeLneRDOj140 = 286
AAAaAAAAaAAaAaAAaaaAAaaAAaaAAAaAaaAaAAAaaaAAAaAAAAaaAaaaaAAAaaAaaAAAaaaAAAAaaaAaaAAaaaAAAaaaAaAaaAAaAaaaaaaAaaaaAaaAaaaAaaAAAAaaAAaaAaaaaa = 497
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd = "OhHMIFpCNyxbopScUNZLjCUrymaBxbUKeIHqIwtdbcrElrIfHjoXjnKpsliYVfQdWIcfkfDitCItqwN"
IIIIIIIIIllllIIIllIlIlllIIlIIIllIIIlllllllIllIIlIlIlIIIlIlIIIIlIIlllllIllIIllIlIllIlIlIIIlIllllIIlIlIIIIIllllllIIIlIlIIIIIIllIllIIlIII = "vPodSJJYORVyAuDVkRLOJQypUTqDMPNWOqDMCtMhWmyPKiWhPLNYtnMSRflTZyizMrRnmyQSLBsaKiM"
AaAAaAAaaaAaAaaAAaaAaaAaAAaAAAaaaaAaAaAaaaaAAAaaAAaaAaaAaaaAAaaaAAaaaAaAaAaAaAaaaAaAAaaaAAAaaAaaAaAaAaAaaaaaAaAaaaAaaaAAAAaaaAAaAaaA = 337
AAAAaaaAaaAAaaAAaaAaaAaaAAAAAaAaAAaAaAaaaaAAAaAAaAaAaAaAAaaAAAaaaAAaaAaaaaAAAaaaaaAaAaAaaAaAAAaaaaaaAaAaAAAAAAaaaAaAaAaAAaAaaAAAAA = 182
h16822114529633128 = "XuxLKeuMFtKhLTDzqQWUPsgafNPUWANPgAQYtMwuCzAUsCbKxytSGrQYIagpPAgPOYlNuNDBGrYqVbZ"
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL = "aBqYAWQUExDhkWmgmxGmAEQuWMmrqohFxCenBOeLqDDqVXsknneUiQpRNeFhkACOXjIBnBHTRTZKXxU"
QICSXZuHszeOYGbaHwQGmqCxIfzAdKaAzUsuGhByuqnkIkVihTpJjSbVHBUWioPlOoXEraTAVQObrwM124 = 360
aAaaaAAAaAAaaAAaAAAaAaAaAaAaAAaAaaaAaaaAAaAaaAAaAAAaAaaAAaaAaAAAaaaaaAAaAAAAaaaAaaAaAaaAAaaAAAaaaaaaaAAAAaaAAaaAaAaaAAaaaA = "tOwjAQllFbUvuRiqkCYoPLEjtovExQxXiTkEoWiMSwzkvSSXjVLxMKYoAfpFHgveCAmLkPMhZyHKrnt"
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS = "tmdGyBhcHbrXAPYtihXfcqhirzZyHpgPuyIsExmYCOvokoyNHdaeRQNPZgvyLNfKicPzRlKcahyuhko"
aaaAAAAaaaaAAAAaaAAaAAaaAaaaAaaaaAAAaaAAaAAAAAaaAaaaAaaAAaAaAaaAaAAAaaaAaaAAAaAaAaAAAAAaaAaaaaAaAAaAAAAaaAAAaaaAaaaaaa = 239
aaaAAAaaAAAAaaaAAAaAaAAaAaAaAAAAAaAAaAAAAaaaAAAAAAaAaAAAaaaAAaaaaaAaaaaaAaaAAaaaAaAaaaAaaAAaaAaaAaaAaaAaAAAAAAaAaaAA = 667
lIlIllllIIllIIlIlIIIIIIIlIIlIlIIIlIIlIllIIIlIlllllllIllIllIlllIIlllIlIIlIIllIlllIIllIIllIllIlIlIlllIlIlllllIIIlIIl = 416
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk = 87
lIlIIlIIlIIIllllIllIlIIlIIllIllIllIIIIIllllIllIIlllIlllIIIIIIIIIllllllIIIIIllIIIIllllIlllIllIIlIlIlIIIlIlIIllI = 535
llIlIIIllllIIIIlIlIIlllIIllIllllIIlllIIIIIllIIllIIIlIlIIllllllIIlIlllIIllIlllIIlIlIlIllIIIIIIllIlIIIlIlIlIII = 419
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = 568
p104 = 254
aaaAaaaAaAAAaaaAaaAaAAaaaaAaaAaAaAAaaaAaaAaaAaaaAAaaAAaaaAaAAaaAaAaaAaAaaaaaAaAAaaaaaAAAaaAAaAaaAaaAaA = 215
h16822114529498107100 = 515
a98 = "FvFZMUecrlsLkEdogUXkhENIDPPTLfVxUKSYATVoglSKIpnqEyXrCayXxICUJtYEvUKEErjgCkzmYNk"
J1682211452949107696 = 313
AAaaaAAaAAAAaAAAaAaAAAAaAAAAaaAAaaaaaaaAaaAaaAAAAaAaaaAAAAaAAAAaAaaAaAAaaaAAaAaAAaAaaaAAAAaAaA = "VsmVmZfCUjOkWAbMnPwzGljuGhQPqGfDbtrDecrdcmYYjxQyEJRlIpqsovBnizseCbfkqTrMVTgljEg"
w92 = "hPKJIUAsetIxweFiUHXndyhNOrpfQYqjGWbhkTLXPUZhFmWlxamwvDasQuvvIqXhqBRouNKjWZTBLcV"
j168221145294462690 = "iinceZEoeuVCXOUTRZrKOmgIHWErGNUigVIAeNdVBRReqJPuZDltjbibZadxGvKAaGCDgsTcZZFykNe"
ONdQVYSTcnhaYHPaaOorUtfmfoLbFzKDoAPIxvzEMIdnMiqclimqwUUVVmybLTVprqWjrrmVBDEyGig88 = 458
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC = 187
D1682211452942546684 = 370
B82 = 57
IIIlIlllIlIIllIlIIlllIlllIlIIllIlIIIIlIIlIlllllllIIIllIllIlIIlllllllIIlIIlIlllll = "RgxZQSDYbCpPcTmcHdKuPMHPicPrNhLBehuaeaAizgceTLcuiRfDeuUdVpGMOdYcObSGEveWvIerxbH"
aaaAAAAAAAaaaaAAAAAaaAaaAaAaaaaAAaaaAAAaaaAAaaaaAAAAAAAAaaaaaaAAAaaAAaaAAAAAaA = 299
lIIIlIIlllIlllIlIlIIIlIllIIIIlIIlIlIIIllIIIIlIlllllllIlIlIllllIlIllIIIllllIl = 528
aaAAAaaaaaaAAaaAAAAaaAAaAAAAAAaAAaAaAAaAaaaaAaAAaAAaAaAaAAAAAaaAAAaaAaaaaa = 330
f72 = 189
YIFTSlPSEDIrHFVBtjygMywBNHTtYZkFsAvNaHAhWCvXinhExufuZpkHlgfwfOtpafAdBkBCKyFnShE70 = 170
IIlllllIIIllIlllIIlIIIlIlIlIlIllllIlllIlIllIIIIllIIIIIlIlIIIlIllllIl = 382
IlIIlllIIIIIIlIIlIIIllIlllIllIIIIIllllIIIlIIlIllIIllllIIIllIllIlII = "JDsiLdanLpzoQZASaDjTiOlizNmdLFeFybRRtsZyPmoaxqAtBUlCqavqhVVELoiogPqItCQSVGFZyct"
EqZUoQpRTZfzfeMsVoXuTliTcAHHmWspcTZEBJzOUazzxraYnnIWyOlizBTOTRDOzkOLkhsxgbSQAiQ64 = 57
c1682211452934271362 = "VybpcmFTjpBluRusrLQPNmPpoSOrTypVIGQxqxfYgxFHsyBIRwoLSrzInxpUreHTJJvpyHTzJFFMhmg"
R1682211452932951260 = 347
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX = 125
IIllIlIlllIIllIllIIlllIlIIIllIlIlIlIllIlllIlIllIllllIIlI = "XUuuqUaUdlDlnxIICTDTzTatEZsjXdCEJOAongSByKjlgSoPCKXfUlSrzEBeEVxwBfnZxDtpbXoedFI"
IIIIllIlllIlIIlIlIlllIIIlIIlIllllIlIlIlllIllIllIIIIIlI = 417
VSFJVEbZdxgwaFufXmWykpbSJaQYeCltVgNwtnHeyirmRKtKCggFiZEClWrFGAbatLGtESVSQBZogLu52 = "lWTRKjcPkHcCPxamPmPtWbPUAVCGjbEHLlSimLDHrOfPOuGvgsYtRlkcMJTIZrdDjFQfpIQFicgXYOq"
FKOVByGGwWpEgRgmUIJAgUneFngilAYyMpKImOuvloXZxOkYXpVrkIyNYaFyngdnemCpcmLCxjSNCEp50 = "jqFsrufoWeQkXhGXvxhAnWMDGRSdfQYwzuhCKXxZVjxuMaRhISzOSSssIgPpRiPjmjtPaTuBxgrsKPf"
W48 = "aZJAZFdTJGgqQKiggvvzXPBWcNGtCGYhKyYEXbRvsjYbAKukFNJwsnsWGdxIvgyAEQfotKuDpaftSWK"
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq = "nwmACKTDuSNQiqVjQJOdXMplrIZzUOYYUFgpWPkzAMQTsjLUBHkUgNzXJhpRdmwKoBKdsvfsWNsEWPU"
x44 = "VJzoumzcdiCZaDYqVIXNwAmkMWERAfxVBvPuDLNIvqojSEpbYMszzdZeSTZAUiRuIWuEwJCLGFLSbJx"
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = "fJBYkKCqUprGtGwTKPpBrhyQqPHHUnXjcLpEAdVoWtXLOpIVvZWgvNHVZKpqrjkBknFIqWIhGtTNpaF"
aaAaAaaaaAaAAaAAAAAAaAAAAAAaaAaaAAAAAaAA = "QtsDDvrakgEBYlAJbigzzQkcuSAHdwLkRBswBfEnwicaDKIoNyafpQajjdrcicQzbWdqgxGNaLkdvNN"
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = "unbCRFLziqtHNnYxixHgizWbnrDTNIrpgbWhHVTPgzSeEHNKcwOXZIVrKbtjEZoifJGfhYlJQfEFWvJ"
IIlIllIlIIIIIllIIIIIIIlllIIlllIIllIl = 305
AaaAAaaAAAaAaAAaaAAaaAaaaaAAAAAAAA = "mYmwnflKuWGMHweRHvBOidAFHaNIZlSuHOEfbCNesvyiTEJJqGQWMZgfAwaeNLdMrzkOkaXnZmQQHbA"
B1682211452918527132 = 836
IIIIlIIlllIIIIlIIlllIIIlIIlIll = "MCLotymJLcoYKXIYSnCuhBqfdtDpDVvGpznkNZTQrZxCPAEjZxYqtNMAAnclPaWAEdhPtFLtOdVaQgd"
aaAAaAaaaaAAAaaaAaAaaaaAaaaA = 334
rZUXdjfWTnhjnlFlYXGNtUktNtWOFHvFVoFKyvLhgaXnFbYOVeoVEVXOFVBGqcVyVvDQQTmXOVvveYb26 = 608
I1682211452915764824 = "FMlHrFZSGrbpdeiRhnVZpqJURBLEXfdHOhvcfOnPauOYCgAHFMmxORCjbOpFHVhoVPDfMeXehemgZIW"
aAaaaaaAaAAAaaAAaAAAaa = "KpzUoZRjilDMXVbtUXdSosnrRAbfweIZtOOTLLfBKFzmEXVWUfptvpJXWDluvPxmGsmYVvYtVkAyfRY"
AAaAaAAaaAAaaaAaaaAa = 348
aAAAaaAAaAAaaAAaAA = 372
IIllIlIIIlIllllI = "xilvvrwtAIXdgYLzbNLsmopiUjyqUiIEJUfsLZlWFihvXlpMiLURjKANEZVEjTQmSrBfTrMGtlIbWbE"
kkkkkkkkkkkkkk = "wsLLWiKHEeQTMiNmKaTNUWbngtyxPXQHGAcQzAGqZGvwxrzQPZpAZiwtDUDQMtkdvXgFdDnuiOKfuPL"
aaaaAAAaAAAa = "PQbXHivXhxelBzQMUjxUzxCIOgCagoCpMLYzGcsSkgtYPoJTeLIsUhxQcWwkYAaijufwIvHVKkzthUt"
E10 = "TjURDVHtkCMbgArXOWyLpGtVoJsTjZiCJcuGZOYQLRXMdfuytmpTdbMsoRyOSmzspKIXqByXSLbthQf"
IlIlllll = 236
kkkkkk = 591
NNNN = 214
c16822114529076382 = "vTsQxHwsYrBbaloAJDFVaSybVkjiMUHsYlUqVECUgyeJdjJItPtcmvgkhRqOpPgGzurAHMJHuxotQCW"

#!/usr/bin/python 
import os
import requests as nabil 
import concurrent.futures 

a = """\033[0;31;40m  

 @@@      @@@@@@@@ @@@           @@@@@@  @@@@@@@  @@@@@@  @@@  @@@
 @@!      @@!      @@!          !@@     !@@      @@!  @@@ @@!@!@@@
 @!!      @!!!:!   !!@ @!@!@!@!  !@@!!  !@!      @!@!@!@! @!@@!!@!
 !!:      !!:      !!:              !:! :!!      !!:  !!! !!:  !!!
 : ::.: :  :       :            ::.: :   :: :: :  :   : : ::    : 
_____________________________________
author: Skid-Dev
_____________________________________   
github: https://github.com/Knownasjohnn
_____________________________________                                      
"""
os.system('clear')
print(a)

lI = str(input("[+] Enter Url(with param): "))
print("")
if "?" in lI:
	lI = lI 
	Z4 = open("Pay.txt","r").readlines()
else:
	print(f"[+] invalid lI(please input lI with param): ")
	exit()

def scan(x):
	lIIll = x.strip()
	BBBBBB = lI+lIIll 
	aivzztJemqVFtUywNHFBATgwXLAGzTxdPuIkkoSkEbgOVXLhrTZjsIeBcPYGhGpBXwGPfOxPVALDbeJ7 = nabil.get(BBBBBB).text 
	if "root" in aivzztJemqVFtUywNHFBATgwXLAGzTxdPuIkkoSkEbgOVXLhrTZjsIeBcPYGhGpBXwGPfOxPVALDbeJ7:
		print(f"[+] FOUND     : {BBBBBB}")
	else:
		print(f"NOT FOUND : {BBBBBB}")
with concurrent.futures.ThreadPoolExecutor() as exe:
	exe.map(scan,Z4)
I = 401
u3 = "XMclqNDtecCuCNzNEyGSXuaeFtuLmnAgkxqYqMZmVhPmUdqPujgOuSPHoWkidunacmfivVQzFzUALGB"
ttttt = 341
lIlIIII = "DFVTDoaLcfLnQoxvRnKcekuhzEaQmXhbXzbwCwzLXzLRAiZcTJmRurSDsdIQYdOjIXPXiGHKDIGnHxI"
AaAaaaAaA = "DLvLjPGwNjltfDQaqDyRbLaolfrwjCsQbsYIdDhIRfisviwdqBCCKPWmfDvfCTagRllmBRDrzfzrgob"
lIlIllIIlIl = 405
llIllllIIIIIl = 386
p1682211452911601815 = 165
lIIIlIllllIIIlllI = "wTYXjCsLImZLTsKpyALnbRSpiuwlUBjtFSEBDtCtDPbcORmeIcUyqTZFsuywmsqUviQTGFzjzCKiOYr"
H19 = "yAJgwdaDjNSwmnDQnZZJHAygfNhwPUTJCKaTZGzjtLpdaOHbJDncEUycYLWNOXxvoyzXhtZCOrYAXvp"
fNXhbybuVXpjgVPueJXqwGFppLPhxGLaRcwdFzhqbFSOojNOPlLLgkmhVJdYNAUELzdvYyyCkEwgTld21 = 161
hAExXtXZYgIeLipdwnwPPsVOTMYwIwGeFYbVAevlTosaTzrJhVQEJWKepQRZoDqrDknbZnCYoJCuUno23 = 342
AAaaAaaaaaAaAAaaAAAaAAaaa = 302
IbJaMSqnrFCRyTOjClRBBmwxKFNBtXJeBySHizmiXCQrrztVRmgJVqTevECtNEEocYctagUWYOouGKl27 = "mxEswgchDpJhbQRRqFuozDJCnRsyjZMsfEREmvANUzSmDHezocoQvsUDjbeLcQvDuBpnMoCFtjjcQgj"
lIlllIlIlllIIIIIIllllIlllIllI = 391
v31 = 601
fffffffffffffffffffffffffffffffff = 788
Z1682211452919777435 = "SMlWORxWOQuhZCPTRLqiWFQNHjERFHTVEhGslraJfZVgTKgqEaCzORuLmZwablwoZLiinpjlGwoANrP"
IIlIlIlllIIlllIIIllllIIllIllIlIIlIlll = "gwWKeEPHWagFEsFCtYVzzhnzOeCzMhbAaxqXPpAbiVsBuyAksUigHqoHDFVUPCyZZSzzeEZWIgNWCaW"
g1682211452921703339 = "pwBmPooLqtxWaWiliZrNdSVeSAUGuSYPlqSOZdgbtSPwZqdsfrhzvmOQVyJEtWoQuLXFAGtKAUyExyi"
AaAaaAAaAAAaAAAaAAaaAaAaaAaAAAaAaaAaAAaaA = 103
HuUhreJSAZBwvioCfNduTPJBzqytrodNErAAttTQCIYWbDYUsoQbWIsPdvKaTuDbjlRSXGNfopuBEaY43 = 298
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk = "vZJoWhRqLdobovlrYFVckgWzqEmDkmWriCyRYWfqozYJruGmHaMEsQjGRfCRiCFDqGbTkwyNFBqlmzX"
T47 = "STcCfgZpIsMSFNmjVwrPTnYhAOcHEkJAePlSxOVZNdHufLOqlvrSjzUCWmaUUyQjkKAeBgBZkUmHBzV"
f168221145292669149 = "pWSFrBgbQsDONanUmOivZRIxvMHpuCAcLNLJBIKExELIvVTTPueeNlNsVTkjHhuoEjlhhitkaZHYbyA"
lIIlIllIIllIIllIIlllIllIIIlIIlIlllIIlIIIIlIIIIIllIl = 518
PtUtxgNOYffVyPItnADsgTGfPqIIdvzPflYLrPZNHUsZxQXZeCOAuncfaHXITtskivFEcMfjLPcWlyl53 = "ftlvNxEccROYiSfipZlBdJTwQnyzoCOSiSCjmKUpEpZvaDqKidEHzEbgchuNTETzsQoSIRtNIlZixXa"
gGcsciGwaxXIGXGqNjmkFNXkLJqgbQgsnNnKxYVZyjjrOSOjQUHCLrSFibUFcuSLpDdmUxizbQeOZyf55 = "tQIWvqNPAHEoLdwqmDjggQZvbjuAPrqRWnlDSKmwnQfoKkadCpPmBncsGUKOQtFaxNnonipUHmnNFAG"
L57 = "QXmlaXMMHKXgVgRCZgjIIFILvwBCFmcwZCFZIwpTCEIyfAQlfnhmhugGqpMuUqtteZjzWOBBDXuMKMk"
kHfEAwEfvJEmbiUkarvlGWvdHkWkLrwgYzWaVYrMOvvuHxgXFyuCcDBfADzUAueiqcGCQNggYWsxSyG59 = 523
aAAAAAAaaAAAaaAAaaAaaaAaaaaaaaAAaAAaaAaaaAAaAAaaAAAAAAAAaaAAA = "pwtwlPoxeociXGxLDtAMPSknAdGsqdeJnmRWnnsTOuiQzVYpVDApDfkVNdaFizlyKoiysrjXsaTkQjp"
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = 204
u1682211452935296365 = "WRvJMVhnibGTToYticruYjjymVgBfrdYaWeLdWMErSPDIdNKVHXxsYrMYmIBvsbXBLtOogMFOJOjEQv"
HXdVOuLZzvrPVMXHsphJObtCQrAXoEqcAjbCKSQbthXaKnyzzGOFvMiyWkBzFuEOSDREQpeJZwFBePd67 = "pOLnvrEVmKMHZqvutLyVkFHpYpOcFplkiEGyjOwvYfValGoYlOHGOPBvLZOadaIHmYQnrxeGxbzUFRW"
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv = 130
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = 654
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = 599
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk = "JtfeXwKoubztFLWGyVLkhrdPxkAsQeoSjgWkSLdolhoJZjoLyeQnGKIocmaLoJMdYedpsovcpvnQezh"
FnOpeBiUhbTbLBRucueWlYcNHvhQRmMYVMLWhmuhomwKHupLoouulByDbzXvOpjIHBzKvJNvLMJOvhx77 = 282
D1682211452940495379 = 622
aAAaaaaaAaAAAaaaAAaaAaaAAaaAaAAAAaaaAAAaAaAAAaAaaAaaAAAAAaAAaAAAaaaAAaAAAaAAAaaAA = 516
AAAaAAaAaAaAAAaaaaaAaaAAaaAAAAAAAAaaaAAAAAAaaaAaaAAAAaaaAAAAaaaaaAAaaaAaaaaaAaAaaaa = 571
g85 = 645
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR = 177
AaAAaaaAAaAaaAaAaAaAaAaaaAaaaAaAAaaAAAaAaaaAaAaaAAaaaaAaAAaAaAAaaAAaaAaaaAaAAaAaaaAaAAAAa = "ujEmBIQaDVBsSNnZtfGrDNOkuhDFXxrkRiTiBbvtEtZCXqlqzhiUOlbXNDmoQIXpMPdSzGGnBGmtpFq"
AaAAAaAaaaAAaAAAAAAaaaaaAAAaAAAAAaAaaAaAaAaaaaAaAaaAaaAAaAAaaaaAAaaAaaaaaAAaAaaAaAAAaAaAAAA = "nlXLSTxhQosunYYEgcKPsrCLWnOGcvLtoGurVkHJHCufLczSBQovJVVCXLMlfJvsQCYpQAVVLrANFDB"
AaAaAaAaaaAAAAAaaaaaaAAaaaaaaAAaaAAaaaaaAaaAaaAaaAAaaAAaaAaAAaAAaAAaAaaaAAaAaAaaAaAAaAaaAAaaA = "HMLQiBQuJyiEazJKLbQgsLxqfxGJRwcanqhiiDHYssrPbPuBejMbOiLstZRZWNYNKmmENmQgfYTZVFJ"
IIlllIIllIIIIIIlIllIllIIlllIIlIlIIIIllllIlIIllIIllIIIIllllIIIlIlIlIIlllllIIllIIIIllIllIllIIlIIl = "tlYaPuigoEAyvnZzipgGPxwDluXsItjTaBwaZMWQOoIntUnxDMEFNbCXRyMEdxeiKrcJFSXNSjJoAGJ"
X1682211452949194797 = 252
W99 = 357
asttbNcNMEbnuXoquUtxWQJpSkxPvuOkVwgyqPkVnlOOAxcXnspKYNvyAjOvghPWicdBzWYHPaWxCXz101 = 569
Q103 = 537
n16822114529510171105 = 765
Q1682211452951135107 = 167
V109 = "fqRFHrowSXNQrnHtndsNjKFSGrczPfcQlRlZfnVKqISxpIPyFvnhmnJNjjAnfhSkDEDyhYqCRDMTUQT"
C111 = "cxQcSfdPsGCgTvLyWNPkyXSOrDjCFKiTZYyHjVJsqpkgryfGftTDyLQHdTPfKJmcelnLkzqJWYfIIpV"
M16822114529548967113 = "KfOCRGVJCLEPwdZAWldcJvCdRTCEzjShLoCByzqpDVilwkpeXCfHOvmDamTgFQOdzsrCPqZYsTWAGCR"
QbYyiiOPexDxPoayQtgbeOAOtGSAWXdQqfCGLLRgLUHZEimBjDZsmVeVNdxyturMICrXrGEZnJiGWwa115 = 348
M117 = 575
y119 = 299
aaAaAaaAAaAaAAAaAAaAAAAaAAAAaaaAaaAAAAaaAAAaAAaaaaaaaaaaAaAAaaAaaAaAaAaaaAAaaaAAAAaAAaaAaaAaAAAaaAAaaaaaaAAaaAaaaaaaAAaAA = "uEaWZNJnXcMfwcgTsdBagSNJWzQAaWooDDGPWyzRkYHeFLEuliQIkGgBlRJcWHbaVfoYTGNlnMXgYVd"
b168221145296046123 = 528
aAAaaaaaaAAaAaAAaaAaAaAaAaaAAAAaAAaaAAAaAAaaaaaAAAAaaAAAAAaAAaAaaaaaAaAAAAAaAaAaaaAaAaaaaaAAaAAaAAAaaaaaaaaaaaAaAAAAaAaAAaaAa = "BBkpcUvXWGbgUUltlVKMotvXDpbsnNuhRarFuieunStiZuMOCWOUPhuMRLOiHHkfhkhUHCElRleObxy"
o16822114529627905127 = 281
u129 = 381
AaaAaAaaAAaAAAAAAaAAAaaAAaaaAaaAaaaaaAaAAAaAaAaAAAaaaaAAaAAaAAAAAAaaaAaAAAAAAaAaaaAaAAAAaAAaAaAaaAAaaAAaAAaAAaAaaaAAaaaaaaaaAAaAaAa = 348
ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ = 542
u135 = 267
AaAAaAAAaAaaAaAaAaAAAaaaaaAaAaAaaAaaaAaaAAaAAaaaaaAaaaaAAaAAAaaaaAAaAaAaAaAaAAAaAAAaAaaaaAaAAaaAaAAaAAaaAaAAaaAaAAaaaaAAAAAAaAAaAaaAaAaAA = 228
IIIlIIlIIlIlIIIIIllIIlIlIIlllIlIIIIllllIlIIIIllIllIIlllIIIlllllIIIIllllIIllIIlllIllIlIIllllIIlllIIIlIIIIIlIlIllllIIIlllIlIlIIIIIllllllIIllI = 188
aAaaaAAAAaAAaaaAAaaaAAaaaAAaAaAAaAAaaaaAAAAaAAAAAaaAaaAAaAAAaAaaaAAAaAaaaAAAaaaaAaaAaaAAAaAaAaaaaaaAAaaaaaaAAaAAAaAaaAaAaAAAAAaAaaaAAaAAAAAaA = "aDfFpxdTNEAZUMWensXaMnDnZSuYWEempGkFCsUsLjQxlgPeqmQiGaoZWrRgiDPQLNyPUmWrGScYdBn"
ioPQUCPAjvntQrLhbDLvULFknZRKAATdeeChdKCXJoTaLOXgNIuvIzgoJrzJNwrgnCMFEYBwoLUhEOu143 = "xyFTTHbhridJxhOHyxisfbeDLBCnsjjgBEBiMzcLzHCoRZutvACXgMGkIxKOGQXejUyVlBrtfkmUdbO"
C145 = "GkwGfiUFroPSkZeyjtCQwLXqhWiJQmuDGKIQJdmQhQpyXfxLyNbqOzxifYfbIJVTCGBtwblxBrvzrDK"
aAaAAAaAaaAaaaAaaaaAaaAAAAAAaaaAaAaaaaaAAaaAAAAAAaAaAaAAAaaAAaAaAAAaaaaAaaAaAAAAaAAAaaaaaAaAaAAAaaaAAaAAaaAaAAaAaaAAaaaaAAAAaAAAaAaaAAaaaaAAaAaaaaa = "EnKftGSmOFtIMqTEIdIHfZsjWmuQtLjTnhNrIJgWnwmWsxdGGgOJIKOAjFBDWwvRWOLbTxBTVCOMPMC"
IIlIIlIIIlllIllIIIIlIIIIlIIIllIlIllIlIlIllllIIlIlIIlIlIlIIIlllIlIIIIllIllIIIIIIIIllIIIlIIlIIlIIllllIIIIllIIIIlIIIllllIIlIlIlIIlIIlIlllIlIlIllIllIIIIl = "LzgoqPgMUUSuVtpOndpxsrNuZJMptSojDbBCalWItlVKRRwwIGRNqkKMsVTjRHVxTGQIAVybWBeoZfn"
IlIllIIIlIIlIllllIIIllllIIIIlIlIlIIlIllllIIIIlllllllIlllIlIlIllIlllllIlIIlIIlIlIIIlIIIIIIIllIlIlIlIlIlIlIIIlIIllIlllIIllIlIIlIlllllllIlIlllIlllIIIlIlIl = 352
ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp = 612
aaaaAAaaaaAaaAaAAAaaaaaAAAAAaAAAaAAAaaaAAaaAaaaaAaAaAAaAAAaAaaAAAAAaaaaaAaAaAAAaaAaaaaAaaAAAaAaAAAaaaAaaaAAAaaaaaaaAaAaaaaaaAaAaAaAaaAAAAaaaaaAaaaAaAaAAAAa = 412
aAaaAAaaAaaAAAaAAAaAaAAAaaAaAAaAaAaaaaaaaAAAaAaAaaaaaAAAaaAaaaAaAAAAaAAAAaaaaaAAaaAAaAaaaAAAAaaaaaaaaaaaaAAAAAaAAaaaAAaaAAAAAaAAaaAAAaaaaaAaaaAaAAAAaaAaaAAAa = 511
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = "aJzLVdgavmQbyiaaDffyyQFkkfxusFogxmMMfrnbaRvwGMiiyioJGLSuVprRDAVOpodBQUFHLEyNSTD"
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB = "KKUrjHUuigAiNshyUOaTgCpKFifIfUWHzFgDuYFoOthzxHMdlZMyfCLMNvFiEJvcTyyGDGsnJCGIeIe"
llIlIlIIIIllIlllllIIllIIIIIIllllIlIllllIlIIIlIllIllIIllIlIIlIlIIlIlIIIlIIIlllllIlllIlllIIIIlIIllIIllIIllllIlllIlllIllIIIIlIIIIlIIIIlIIIllIIIllIllIlIIIIIllIIIlIlIll = 367
q16822114529887722165 = "SdbVbjykFogvwLkUnfxQXgqgAEHOJugAqHTpDWUhuPRrtwMXjnJRVlshXyKfOMXppxqlECvTiKTveHm"
VfcQXPQVZOCMfQvidsgnKFBqELtUKGFdqOsChNxpjfajFKVGCarzvVJKKGSCAJqwetmSWGDblOdHYvu167 = 784
IIIIIlllIIIIIlIlIIIlllIllIIIIIIIIllIlIIIIlllIllIlIllllIIIllllIllIllIllIIIIlIlllIIlllllIllllIllIIlIllllllllllIlIIIIIIIlIIIIIIlIlIIIlIIlIIlIlIllIllIlIlIllIIllIIllIllIIIlll = "EsSlNtkLbVJZrhpsJDSfyROlHxnbhjWKjwtbOfygqpnchFGRAHnOQWiqkTYosSMQdjPorPEgtAUQVjd"
x171 = "oxBKCarGeSVFFZUmscIYcbmAoYgsjaDwxrOqHXaChMOwZtUOXZFBldbgOkgMIrtzrNUxOpbhMGSWQTs"
H173 = "bFKfHnvQLWlGRLZfGuxyJBfswctIIaYmblFafBbcxFaUuJsypdgFDylVJMpcZESlBOANhMjGmzZmioE"
t175 = "ufJKkRGknzJeumAnTZbVYLiQNkpGqlBlvDDigJBnaaUogBqYduLugjipZJrcSokraPCCururxIVUKMs"
t177 = 584
KriAdrhuvGCowRulaBDrnauYjcJRkLmVensEWQzOudEiARYudvPAHyhOEaATlqybMEsxEnHEoWAlLnX179 = "IwzRSwsejWNaVViJSiXmwKugjeENjPiTfUPtwwcsrqQlTstlJRIiyGrCnPitFsmXkOymDaJWiWujsfy"
J181 = 368
llIIlIlllIlIIlllIIIIIlIIIIllllIlIlIlllIlIlIllIIIlIIlIIllllIIIIllIIllIlIIllllIIllllllIIIlIllllIIIlllllIlIllIlIlllIllllIllIllIIIlIIIIlllIlIllIIIIllllllIlIllIIIIIIllIlIlllIlIllIIIlllIlIl = 131
ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd = "aAXXcSwkXbQDuZtzmUPmdWZLgdRrlguINvrMneLdXIRuuFrxftcCgRVFZbMTwYgjqBWhbqxUCiquqwh"
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = "aijPfsHDdFUVhFLciITACRYuCMoCrfhdheEFYgxfMULbdAPgblyLbdAgtOBFtGrecMsSvxkEXAUfeSL"
NcUnULrQgUbxPWwUgXfcdYaUsauySTkynWoFVjVefYeKsjgmHdRichjmbQQAQyHdFiTrsESTcTngeKU189 = "ARhNklkMsskFSVrJRmSzFipxygbDXUtQlGzZrGbUxJDDhoobEmArQtWLbhJSMTVKHNjMIZpVPHcmpsa"
FCceUbFvzByMzCjbGrHrfnvdgQztIaCXvNlIOrMfohxtWEtmcImBQSWppeuUrmfUEvCikqkJpsKovVs191 = "OLoTwMHqsXmxmbVmlbrRmSPRtAuATOguUwHyINTECGEBjvpzbHMDjwlNjIVyAjHTyBgxvaPYDTYCIfY"
v193 = 608
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC = "KrQgmxTNPBeqSnTSVcRFdKURaLisDciavkxnIosBdlYyklzNWjyukLgBsRZtoOlxMQpIxvnATAknNPI"
IlllllIllIIIIllIIlllIllllIIIlIlIlIIIlIllllIIIlIIIIIlIIlIllIIlIIIllIlIIIllIIlllllIIIllIIIIIllIllIllllIIlIlllIIIIIIIlIIlIIlIIllIlIllIlIIIlIIIllIlllIIIIIIIlIIIIlIIIlIIIIlIIlIlIIIlIIIlIllllllllllIlllll = 355
dJgYihGJqsxBDeuMcoxjVAzWjPvEzbIOORRgEMsqMaaYSOvzPsvfohOkTFzVUCnabuciQafeYePWRNd199 = "UAbtJgqyZBmHYtVgbDlwAXiprNrNVzKlaOinTvPoRPTBFTjBYRSAvGFPYHJyUAhJLTPCPrnJIiQuoHB"
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv = 614
AaAaaaAAaaaAaaaAAaaaAaaAaAAAaaaAAaAaaaAaAAaaaaAAAaAaaaAAAAAaAaaaAaAaAaAAAaaAAAAaAAAaAaAaaAAaaaaAAAaaAAAaAaAAAaaaaaAaAAaAAAAaaaAaAAAAAaAaaAAAaaAAaaAAaAAAAaaaaAAaAaAAAaaaAAAAAaaAaaAAAaAAaaaAAAaAaAaaaAaAaaa = "PAHhMJwXzXCXkdoDPfOnGtGEnRlBNZimouJdSyriwbxFbygZMlAhxQZfnaxYExdxLaKubdiYuvkevyg"
M16822114530195508205 = 748
E207 = 303
lIIlIIIlIIIllIIlIlIIlIlIlIIIllIIlIllIIIlIlIllIIIIllIIlIIIlllIIlllIllIllIlIIlllIlIIlllIIllIlIIIlIIIIIlllllIIIlIIIlIIIllllIIlllIllIlIlIIllIIIlIIlIlIIIlIlllllIllIIIlIIIIIIIIIIIIlIIIlIllIIlllIlllIlIllIlIllIIlIlIIl = 542
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 295
BBsJNCVtWwSaieQttDXdqGTdSJlBPJtetGBtAyRvGdFFatgwMcInTkYhQpHnDxysnmiCruJOFvAFjHb213 = 184
AaAaAAaAaaAAaAAaAaaAaAAaAAaaaaAaAaaaaAaaaAAaAAaAaaaaAAaaaAaAaaAaAaAaAAAaAaAaaAaAaAAaaAAaaAaaAAAAaaAaAAAAAaAaAaaaaaAaAaaAaAaAaaAAaaaAAAaAaaAAaaAaAaAaaaaAaaaaAAAaAaAAAAaaaaAAAAAaAAaAaAAaAaAAAAAAaAaAAAaaAaAAAAaAaAAaAaa = 431
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh = "JfvWlNzkaQJAOsSiiLFpfoWfZMqMmIVvsBeaCEmzEVUFXwjvvDDBBBLabYToQLQWXnKsLXvKagvwrEk"
K16822114530274704219 = "JTWcQKHrMwQsrzJSuoswlBtjpHHzaDjJSfQqscRwFnRlmzhwlSrOrNfsBDKidrqXPjZvkwAAZUJxdqx"
d16822114530284815221 = "qHBneYsNqYmrisUKYtMTXduUFPtscewmfeofaHQARBvrebRuDaulWxCYghAERYYuOyBQTenTcdjcfpX"
AaAaaaAaaaaaAaaAaaAaAAaAAaaaAAAaAaAaaAaaaAaaaaaAAAaAAaaaaaaaAAaAAAAaAaAAAaaaaAaAaAaAAAAaAAaAaaaaAAAAaAaaAAaaAAAaAaAaaAaAaAAaaaaaAAAAaAAAaAaAaAaAaaaAaaAaaAaaaAAAaAAaaaAaaaAAaAaaaaaAaaAaaaaAAaaAaaaaaAAaAAAaAaaaAaAAaaAaAaAaaAA = 241
AAAAaAaaaaAaAaaAAAaaaAAAAAaAAaaAAAaaAAaAAaAAaaaAaaaaAaAAaaaaAAAAaAaaaAAAAAaAAAAAAaaAaaaAaAaAAAaAAAaAAaaaAAAaaAaAAaaaaaaAaaAaAAaAAAaAaAAaaaAaaaaaaAaaaAaAAaAaaAaaaAAAAAaAaAaaaaaAaaaAAAaaAAaaAAaAAaaaaAaaaaaAaaAaaAaAAAAaAAAaAaaaa = 851
T16822114530343199227 = "WXrDPMDTIOTVWejmVtbUWNPUNPwoxVHOxnZCTcrjKVDJRPVXSnEnyAJDWETlvaWUjlaYlhTfvSIsczX"
aAaAaaAaAaaAaaaaaAaAAAaAAaAaAaAAaAaAAAAAAAAaAAAaaaaaAAaAaAaAaaAAaaAAaaaAAAAaAaaaAAaAAAAaAAAAAaaaaaAAaAAaAaAAaAAaaaAaAaAaaaaAaAaaaaaaAAaAaaaAaaAaaaaAaAaAAAaAAAAAAAaAAaAaAAAAaAAAaaAAaaaaAaaAaAAaAAaAaAAaaaaAaaAaaaAAAaaaaAAAaAAaaaaAA = 119
EIbVOtNJRAQoRHmmYDMjCYxCArloITlBGKEtbUynSHYOepEDxbEDtzGeldNQNkuxnQHPMKjjDWPXbzH231 = "qLTgKjmdMHlfyXwWGAcbENTWtfUsaSCZIgzKItkjoCQsYpSRnyyjuSKRklrdIRrHGadDdMMjueSlHdk"
AaaaAaAAaaAaAAAaaAAaAaaAAAAAAaaAaaaaaAaAaAAAaaaAAAAAaaaAAAaaAAaAAaAaaaAAAaAaAaaaaaaaaaaaAaAaAaaaAAAAaaAAAAaaaaAaaAaAaaaaaAAaaAAaaaAaaAAaaAaaAaaaaaAaaaaaaAaAaAAAAaaAaaaaaaAAaAAaAaAAaAaAaAaAaaaAAaaAAAAaAaAAaAaAAaAAaAAAAAAaAAaaaaAaAaaAa = "EzAWngQDCYYLNpVZwZXMNERPbcHKhebPBNIHqGZhqlmyGeDiYhLAJCRuihJbNbPMVjIKGSowEkxZoca"
U16822114530396369235 = "dHFTjXVfKdJSnkKqUTkirwpdNRVkYWkRgmpRDGlVnrncehkgBOyzvJNwapdKNbphcHYzLBccpVnzBto"
aaaaaAaaAAaaAAaAAAaaaAaAaaaAAAaaaaaAaAAaaAaaaaaAaAAAAAAAaaaAAAAaaaAAAaAaaaAAAAaAAaaaAaaAaaaAaAaAaAaaAAaAaaaaAaAAaaaaAAAAaaaAAAaAaAaAAAaaaAaAAaAAaaAAAaaAaaAAaAAaAaaAaAAaAaAaAAaaaaaaAAaaAaAaaAAAAAAaAaaaaaAAAaaaAAAaAaAaaaAAaaAAaAaaaAAAAaaAA = 555
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss = "aZSXWljmhQjRSzoytdofPKcpecbzrvhoeXhHupXgvtHptaIDDSYFMJgzwUyhBpcmTdSkTtaLpeEYthn"
lIlIIlIllIIlIIIIlIlIlllIllIIllIIlIlIIlllllIIlIIlIIIlllIIlIIIIlIIIllIIlIlIIllllllllllIlIlIIlIlllIllIllllIllIIllIlIIIIIlIIllIllllIIlIIlllIIIIIlIlIlIllllIllIlIlllIlllIllIllllllIIllllIIlllIIIIlIIllIlllllIllllIIIIlIllIIIIIlllIIIlIlIIIlllIIlIIlIII = "ZPIpbVHVgtmGvinFMjlhlMfYNEsuXWFePpshkKTMhHwaWnQEkjpzsDehMsVKTYgBLyGbVjiCbBEufxn"
AaAaAaAAAAaAaAAaAAAAAaaAaAAAaAAaaaAAAAAaAaAaAAaaaaaaaAAAAAaaAaaaaAaaaAAaaAAAAaAaAAaaaAaaaAaaAaAAaAaAAaAAaaaAAAAaaAaAaaAAaaAaAAAaAaaaaaAAAaaAaAAAaaAaAAAAAAAaaaaAaaAaaaAAaaAAAaAAAAAAAaaaaAAAAaaAaaAaaAAAAaaaAaAaaAaaAaaaAAAaAaAAaaaaaaAaaaaaAAAAaaA = 340
aaaaAAAaAAAaaAaAAAAAaaaAAaaaaaAAAAaaaAaaaAAaaaaAAAAAaAaAAAaAaAaaaaAAAAaAAaaaaaAaAAaAaAAaaAAaAAaAaAaAAaaAAAAaAaaaAAaaAAaaAAaaaaAaAaaAaaAaaaAAAaaAaaaAaaAaaAAAaaAAaaaaAAAaaAaAaaaAAaaaaAAaAAAaaAaAaaAaAaAAAaAaAaaAAAaaaaaaAaAAaaAaAAAaAaaaAAaAaaaAAaaaa = "ikcIWGkaYVboHGBuwNXJjfgtGjIcSIlyflOjJQKRGEBZIVvAbhevwahrkDTLlesttLOfnxTdrgIxoxM"